
import nuflux
import numpy as np
import matplotlib.pyplot as plt
flux1 = nuflux.makeFlux('BERSS_H3p_lower')
flux2 = nuflux.makeFlux('BERSS_H3p_central')
flux3 = nuflux.makeFlux('BERSS_H3p_upper')
flux4 = nuflux.makeFlux('sarcevic_min')
flux5 = nuflux.makeFlux('sarcevic_std')
flux6 = nuflux.makeFlux('sarcevic_max')
flux7 = nuflux.makeFlux('BERSS_H3a_central')
flux8 = nuflux.makeFlux('bartol')
flux9 = nuflux.makeFlux('honda2006')

nu_type1=nuflux.NuMu
nu_type2=nuflux.NuE
nu_cos_zenith =1.0
x = np.arange(start=150, stop=400, step=1)
nu_energy=10**(x/50) # in GeV
fluxmu1=flux1.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe1=flux1.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu1)
plt.plot(nu_energy,fluxmu1+fluxe1,color='red', linestyle='dashed', linewidth = 1)
fluxmu2=flux2.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe2=flux2.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu2)
plt.plot(nu_energy,fluxmu2+fluxe2,color='green', linestyle='solid', linewidth = 3)
fluxmu3=flux3.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe3=flux3.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu3)
plt.plot(nu_energy,fluxmu3+fluxe3,color='blue', linestyle='dashed', linewidth = 1)

fluxmu4=flux4.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe4=flux4.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu1)
plt.plot(nu_energy,fluxmu4+fluxe4,color='black', linestyle='dashed', linewidth = 1)
fluxmu5=flux5.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe5=flux5.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu2)
plt.plot(nu_energy,fluxmu5+fluxe5,color='cyan', linestyle='solid', linewidth = 3)
fluxmu6=flux6.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe6=flux6.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu3)
plt.plot(nu_energy,fluxmu6+fluxe6,color='pink', linestyle='dashed', linewidth = 1)
fluxmu7=flux7.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe7=flux7.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu3)
plt.plot(nu_energy,fluxmu7+fluxe7,color='brown', linestyle='solid', linewidth = 3)
fluxmu8=flux8.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe8=flux8.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu3)
plt.plot(nu_energy,fluxmu8+fluxe8,color='black', linestyle='dotted', linewidth = 2)
fluxmu9=flux9.getFlux(nu_type1,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
fluxe9=flux9.getFlux(nu_type2,nu_energy,nu_cos_zenith)*(nu_energy**2.5)
print(fluxmu3)
plt.plot(nu_energy,fluxmu9+fluxe9,color='black', linestyle='dashed', linewidth = 2)
plt.fill_between(nu_energy,fluxmu6+fluxe6, fluxmu4+fluxe4,facecolor='wheat',alpha=0.5)
plt.fill_between(nu_energy,fluxmu1+fluxe1, fluxmu3+fluxe3,facecolor='khaki',alpha=0.5)
plt.xlabel('Energy(GeV)', fontsize = 20)
plt.xlabel('Energy(GeV)', fontsize = 20)
# naming the y axis
plt.ylabel(r'$\phi_{\nu_{\mu}+\nu_e}E^{2.5}[GeV^{1.5} cm^{-2} s^{-1}sr^{-1}]$', fontsize = 20)
plt.xlim(1e3, 1e8)
#plt.ylim(10**(-6), 0.1)
plt.xscale("log")
plt.yscale("log")
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
# plt.title('Flux versus Energy for BERSS_H3p)(cos_zenith=1.0)' , fontsize=15)
plt.legend(["BERSS_H3p_lower", "BERSS_H3p_central","BERSS_H3p_upper","ERS_min","ERS_std", "ERS_max","BERSS_H3a_central","Bartol","Honda et al."], loc ="lower left", fontsize=13)
plt.show()   

